Repository YetAnotherTranscendenceTeam/ft_transcendence, pull requests merged in 2025-04, with the labels that each got.

#84 Docker images actions
  .github/workflows/push-images.yaml
Labels: conf

#88 Fastify server shutdown
  dev-tools/service-template/srcs/app/builder.js
  services/CDN/api/srcs/app/builder.js
  services/avatars/srcs/app/builder.js
  services/credentials/srcs/app/builder.js
  services/db-profiles/srcs/app/builder.js
  services/documentation/srcs/app/builder.js
  services/fortytwo-auth/package-lock.json
  services/fortytwo-auth/srcs/app/builder.js
  services/google-auth/srcs/app/builder.js
  services/lobbies/srcs/app/builder.js
  services/matchmaking/srcs/app/builder.js
  services/password-auth/srcs/app/builder.js
  services/registration/srcs/app/builder.js
  services/settings/srcs/app/builder.js
  services/social/srcs/app/builder.js
  services/social/srcs/utils/ConnectionManager.js
  services/token-manager/srcs/app/builder.js
  services/users/srcs/app/builder.js
Labels: backend

#97 fix: ibertran docker compose missing 2 matchmaking env variables
  docker-compose.ibertran.yaml
Labels: bug

#98 FIX yatt-modules
  modules/Dockerfile
Labels: bug, conf

#107 Tournament team insert order
  services/matchmaking/srcs/Tournament.js
  tests/srcs/matchmaking/tournament.test.js
Labels: backend

#108 92 profiles get
  Makefile
  documentation/backend.yaml
  services/db-profiles/srcs/routes/root.js
  services/users/srcs/routes/root.js
  tests/srcs/db-profiles/get-profiles.test.js
  tests/srcs/users/filters.test.js
Labels: backend

#118 Production test
  .env.template
  .github/workflows/production-build.yaml
  services/frontend/Dockerfile
Labels: conf

#134 fix: fix google ids not being stored properly
  services/credentials/srcs/routes/google.js
  services/db-profiles/srcs/utils/adjectives.js
Labels: backend

#146 Local Game
  modules/pong/src/core/Pong.ts
  services/frontend/src/components/Babylon/PongClient.ts
  services/frontend/src/components/Game/WinnerModal.tsx
  services/frontend/src/components/Profile/ProfileCard.tsx
  services/frontend/src/components/Profile/SocialFollowCard.tsx
  services/frontend/src/components/Profile/SocialUserCard.tsx
  services/frontend/src/contexts/usePong.tsx
  services/frontend/src/templates/templates.css
  services/frontend/src/views/Home.tsx
  services/frontend/src/views/LobbyView.tsx
  services/frontend/src/views/LocalView.tsx
  services/frontend/src/views/ProfileView.tsx
  services/frontend/src/views/TournamentView.tsx
Labels: enhancement, frontend

#152 94 password policy
  docker-compose.yaml
  modules/yatt-utils/srcs/schemas/properties/credentials.js
  modules/yatt-utils/srcs/schemas/properties/profiles.js
  services/CDN/.avatars/steve.png
  services/frontend/src/components/Auth/LoginForm.tsx
  services/frontend/src/components/Auth/RegisterForm.tsx
  services/frontend/src/components/Settings/AccountForm.tsx
  services/frontend/src/components/Settings/ProfileForm.tsx
  services/frontend/src/config.ts
  services/frontend/src/ui/Input.tsx
  tests/srcs/social/follow-limit.test.js
  tests/srcs/username-regex.test.js
Labels: enhancement, frontend, backend

#157 Avatar settings frontend
  services/frontend/src/components/Auth/RegisterForm.tsx
  services/frontend/src/components/Auth/auth.css
  services/frontend/src/components/Settings/AccountForm.tsx
  services/frontend/src/components/Settings/ProfileForm.tsx
  services/frontend/src/components/Settings/settings.css
  services/frontend/src/hooks/useAvatars.ts
  services/frontend/src/ui/AvatarDeletionModal.tsx
  services/frontend/src/ui/ImageSelector.tsx
  services/frontend/src/ui/Input.tsx
  services/frontend/src/ui/PopHover.tsx
  services/frontend/src/ui/ui.css
Labels: enhancement, frontend

#159 fix: fix avatar service missing import
  services/avatars/srcs/app/builder.js
Labels: bug, backend

#162 wrong useLobby deconstruction
  services/frontend/src/hooks/useSocials.tsx
Labels: bug, frontend

#163 Disabled image selector button when limit reach.
  services/frontend/src/components/Settings/ProfileForm.tsx
  services/frontend/src/components/Settings/Settings.tsx
  services/frontend/src/components/Settings/settings.css
  services/frontend/src/hooks/useAvatars.ts
  services/frontend/src/index.css
  services/frontend/src/ui/AvatarDeletionModal.tsx
  services/frontend/src/ui/ImageSelector.tsx
  services/frontend/src/ui/ui.css
Labels: enhancement, frontend

#161 Lobby update
  documentation/asyncapi/lobbies.yaml
  modules/yatt-lobbies/src/GameMode.ts
  services/frontend/src/App.tsx
  services/frontend/src/components/Auth/auth.css
  services/frontend/src/components/Lobby/ConfirmLobbyLeaveModal.tsx
  services/frontend/src/components/Lobby/LobbyCard.tsx
  services/frontend/src/components/Lobby/LobbySettings.tsx
  services/frontend/src/components/Lobby/lobby.css
  services/frontend/src/components/Menu/Menu.tsx
  services/frontend/src/components/Menu/menu.css
  services/frontend/src/components/Online/ModeButton.tsx
  services/frontend/src/components/Online/SelectModeOverlay.tsx
  services/frontend/src/components/Online/online.css
  services/frontend/src/components/Tournament/TournamentCard.tsx
  services/frontend/src/components/Tournament/tournament.css
  services/frontend/src/contexts/useAuth.tsx
  services/frontend/src/contexts/useLobby.tsx
  services/frontend/src/index.css
  services/frontend/src/templates/Overlay.tsx
  services/frontend/src/ui/Accordion.tsx
  services/frontend/src/ui/CopyButton.tsx
  services/frontend/src/ui/SegmentedControl.tsx
  services/frontend/src/ui/ui.css
  services/frontend/src/views/LobbyView.tsx
  services/lobbies/srcs/Lobby.js
  services/matchmaking/srcs/GameModes.js
  tests/srcs/lobbies/lobbies.test.js
  tests/srcs/matchmaking/tournament-queue-restriction.test.js
  tests/srcs/matchmaking/tournament.test.js
Labels: enhancement, frontend

#168 Add id on all inputs
  services/frontend/src/components/Auth/LoginForm.tsx
  services/frontend/src/components/Auth/RegisterForm.tsx
  services/frontend/src/components/Online/SelectModeOverlay.tsx
  services/frontend/src/components/Profile/SocialManager.tsx
  services/frontend/src/components/Settings/ProfileForm.tsx
  services/frontend/src/ui/ImageSelector.tsx
  services/frontend/src/ui/Input.tsx
  services/frontend/src/ui/ui.css
Labels: enhancement, frontend

#169 chore: add refresh token debugging logs
  services/token-manager/srcs/routes/refresh.js
Labels: bug, chore

#171 153 friends api
  documentation/asyncapi/social.yaml
  documentation/backend.yaml
  services/db-profiles/srcs/routes/root.js
  services/frontend/src/hooks/useSocials.tsx
  services/settings/srcs/routes/account.js
  services/social/srcs/app/database.js
  services/social/srcs/app/router.js
  services/social/srcs/routes/blocks.js
  services/social/srcs/routes/follows.js
  services/social/srcs/routes/friends.js
  services/social/srcs/routes/requests.js
  services/social/srcs/utils/Client.js
  services/social/srcs/utils/ConnectionManager.js
  services/social/srcs/utils/dbAction.js
  services/social/srcs/utils/eventsConfig.js
  services/social/srcs/utils/userInfos.js
  tests/dummy/friendship.js
  tests/dummy/social-dummy.js
  tests/srcs/settings/account/patch.test.js
  tests/srcs/social/follow-limit.test.js
  tests/srcs/social/follow.test.js
  tests/srcs/social/friends.test.js
  tests/srcs/social/limits.test.js
  tests/srcs/social/websocket/blocks.test.js
  tests/srcs/social/websocket/connection-limit.test.js
  tests/srcs/social/websocket/follow-unfollow.test.js
  tests/srcs/social/websocket/friend-request.test.js
  tests/srcs/social/websocket/inactivity-offline.test.js
  tests/srcs/social/websocket/inactivity-online.test.js
  tests/srcs/social/websocket/keep-online.test.js
  tests/srcs/social/websocket/lobby-invitations.js
  tests/srcs/social/websocket/lobby-requests.js
  tests/srcs/social/websocket/offline-follows.test.js
  tests/srcs/social/websocket/ping-after-inactivity.test.js
  tests/srcs/social/websocket/reconnection.test.js
  tests/srcs/social/websocket/status-change.test.js
  tests/srcs/social/websocket/status-nochange.test.js
  tests/srcs/social/welcome.test.js
Labels: backend

#179 feat: limit lobby invitations/requests to friends
  services/credentials/srcs/routes/google.js
  services/credentials/srcs/utils/createProfile.js
  services/credentials/srcs/utils/dbAction.js
  services/social/srcs/utils/Client.js
  services/social/srcs/utils/activityStatuses.js
  services/social/srcs/utils/dbAction.js
  services/social/srcs/utils/eventsConfig.js
  tests/dummy/social-dummy.js
  tests/srcs/social/websocket/blocks.test.js
  tests/srcs/social/websocket/friend-request.test.js
  tests/srcs/social/websocket/keep-online.test.js
  tests/srcs/social/websocket/lobby-invitations.test.js
  tests/srcs/social/websocket/lobby-requests.test.js
Labels: enhancement, backend

#184 Cookie maxAge
  modules/yatt-utils/srcs/http/cookies.js
  modules/yatt-utils/srcs/index.js
  services/fortytwo-auth/srcs/routes/callback.js
  services/google-auth/srcs/routes/root.js
  services/password-auth/srcs/routes/root.js
  services/registration/srcs/routes/root.js
  services/token-manager/srcs/routes/refresh.js
Labels: bug, backend

#186 Gamemode undefined
  services/frontend/src/components/Online/SelectModeOverlay.tsx
  services/frontend/src/templates/Overlay.tsx
Labels: bug, frontend
